(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},e;if("function"==typeof Object.setPrototypeOf)e=Object.setPrototypeOf;else{var f;a:{var g={h:!0},h={};try{h.__proto__=g;f=h.h;break a}catch(a){}f=!1}e=f?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var k=e;
function l(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(k)k(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(b,c);n&&Object.defineProperty(a,c,n)}else a[c]=b[c]}var m=this||self;function p(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};function q(){}q.prototype.toString=function(){return r(t(u(this.constructor)))+"@"+r((v(this)>>>0).toString(16))};q.prototype.a=["java.lang.Object",0];function v(a){return a.f||(Object.defineProperties(a,{f:{value:++w,enumerable:!1}}),a.f)}var w=0;function x(){}l(x,q);x.prototype.g=function(a){this.b=a;if(a instanceof Object)try{a.i=this}catch(b){}};function y(a){z(a.b)&&(Error.captureStackTrace?Error.captureStackTrace(A(a.b)):A(a.b).stack=Error().stack)}x.prototype.toString=function(){var a=t(u(this.constructor)),b=this.c;return null==b?a:r(a)+": "+r(b)};x.prototype.a=["java.lang.Throwable",0];function B(){}l(B,x);B.prototype.a=["java.lang.Exception",0];function C(){}l(C,B);C.prototype.a=["java.lang.RuntimeException",0];function D(){}l(D,C);D.prototype.a=["java.lang.IndexOutOfBoundsException",0];function A(a){var b=z,c=E;if(null!=a&&!b(a))throw a=r(t(F(a)))+" cannot be cast to "+r(t(u(c))),b=new G,b.c=a,y(b),b.g(Error(b)),b.b;return a};function H(){}l(H,q);H.prototype.a=["java.lang.Number",0];function I(){}l(I,H);I.prototype.a=["java.lang.Double",0];function G(){}l(G,C);G.prototype.a=["java.lang.ClassCastException",0];function E(){}function z(a){return a instanceof Error}E.prototype.a=["Error",0];function J(){}l(J,D);J.prototype.a=["java.lang.StringIndexOutOfBoundsException",0];function K(){}l(K,q);K.prototype.a=["java.lang.Boolean",0];function L(){}L.prototype.a=["<native function>",1];function M(){}l(M,q);M.prototype.a=["<native object>",0];function F(a){var b=typeof a;if("number"==b)return u(I);if("boolean"==b)return u(K);if("string"==b)return u(N);if(Array.isArray(a))return O(a);if(a instanceof q)return u(a.constructor);if(a)return u("function"==b?L:M);throw new TypeError("null.getClass");};function O(a){return(a=a.b)?u(a.l,a.j):u(q,1)};function N(){}l(N,q);function r(a){if(null==a)a="null";else{var b;Array.isArray(a)?b=t(O(a))+"@"+(v(a)>>>0).toString(16):b=a.toString();a=b}return a}N.prototype.a=["java.lang.String",0];function P(a,b){this.b=a;this.c=b}l(P,q);function t(a){var b=a.b.prototype.a[0];0!=a.c&&(3==a.b.prototype.a[1]?b=a.b.prototype.a[2]:b="L"+r(b)+";");return r(Q("[",a.c))+r(b)}function R(a){return r(a.b.prototype.a[0])+r(Q("[]",a.c))}function S(a,b){b=a.lastIndexOf(b)+1;var c=a.length+1;if(0>b||b>=c)throw a=new J,a.c="Index: "+b+", Size: "+c,y(a),a.g(Error(a)),a.b;return a.substr(b)}
P.prototype.toString=function(){return String(0==this.c&&1==this.b.prototype.a[1]?"interface ":0==this.c&&3==this.b.prototype.a[1]?"":"class ")+r(t(this))};function Q(a,b){for(var c="",n=0;n<b;n++)c=r(c)+r(a);return c}P.prototype.a=["java.lang.Class",0];function u(a,b){var c=b||0;return p(a.prototype,"$$class/"+c,function(){return new P(a,c)})};function T(){window.console.log("App JsConstructor")}l(T,q);T.prototype.register=function(a){window.console.log("before register ");window.console.log(JSON.stringify(a));this.b=a;window.console.log("register "+r(S(S(R(F(a)),"."),"$")))};T.prototype.start=function(){window.console.log("start "+r(S(S(R(F(this.b)),"."),"$")))};T.prototype.a=["org.treblereel.gwt.xr.app.App",0];T.prototype.name="ZZZZ";var U=["application"],V=m;U[0]in V||"undefined"==typeof V.execScript||V.execScript("var "+U[0]);
for(var W;U.length&&(W=U.shift());)U.length||void 0===T?V[W]&&V[W]!==Object.prototype[W]?V=V[W]:V=V[W]={}:V[W]=T;}).call(this);
